CREATE TABLE IF NOT EXISTS Blog (
	id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
	title VARCHAR(256) NOT NULL,
	content VARCHAR(256) NOT NULL,
	create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	delete_at TIMESTAMP
);
